"""epics parent + issue links

Revision ID: 07e2ab742054
Revises: c24aa8d548ba
Create Date: 2026-06-12 09:49:35.166765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e2ab742054'
down_revision: Union[str, Sequence[str], None] = 'c24aa8d548ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add the new 'epic' value to the tasktype enum (PG16 allows ADD VALUE in a tx).
    op.execute("ALTER TYPE tasktype ADD VALUE IF NOT EXISTS 'epic' BEFORE 'task'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('link_type', sa.Enum('blocks', 'blocked_by', 'relates_to', 'duplicates', name='linktype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_links_source_id'), 'task_links', ['source_id'], unique=False)
    op.add_column('tasks', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tasks_parent_id'), 'tasks', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_parent_id'), table_name='tasks')
    op.drop_column('tasks', 'parent_id')
    op.drop_index(op.f('ix_task_links_source_id'), table_name='task_links')
    op.drop_table('task_links')
    # ### end Alembic commands ###
