"""jira fields + task comments

Revision ID: 14fdecbabdc9
Revises: f04a33a1ee1a
Create Date: 2026-06-12 09:27:00.827028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14fdecbabdc9'
down_revision: Union[str, Sequence[str], None] = 'f04a33a1ee1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the new enum types first (autogenerate doesn't emit these for
    # add_column, so the ALTERs below would fail referencing missing types).
    bind = op.get_bind()
    sa.Enum('task', 'story', 'bug', name='tasktype').create(bind, checkfirst=True)
    sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_comments_task_id'), 'task_comments', ['task_id'], unique=False)
    op.add_column('tasks', sa.Column('type', sa.Enum('task', 'story', 'bug', name='tasktype', create_type=False), server_default='task', nullable=False))
    op.add_column('tasks', sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority', create_type=False), server_default='medium', nullable=False))
    op.add_column('tasks', sa.Column('labels', sa.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('tasks', sa.Column('story_points', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'due_date')
    op.drop_column('tasks', 'story_points')
    op.drop_column('tasks', 'labels')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'type')
    op.drop_index(op.f('ix_task_comments_task_id'), table_name='task_comments')
    op.drop_table('task_comments')
    # ### end Alembic commands ###
    bind = op.get_bind()
    sa.Enum(name='taskpriority').drop(bind, checkfirst=True)
    sa.Enum(name='tasktype').drop(bind, checkfirst=True)
