"""sprints + task sprint_id

Revision ID: 5045eb8610b5
Revises: 07e2ab742054
Create Date: 2026-06-12 09:56:41.704099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5045eb8610b5'
down_revision: Union[str, Sequence[str], None] = '07e2ab742054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('state', sa.Enum('planned', 'active', 'completed', name='sprintstate'), server_default='planned', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.add_column('tasks', sa.Column('sprint_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tasks_sprint_id'), 'tasks', ['sprint_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_sprint_id'), table_name='tasks')
    op.drop_column('tasks', 'sprint_id')
    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_table('sprints')
    # ### end Alembic commands ###
