"""issue keys + activity log

Revision ID: c24aa8d548ba
Revises: 14fdecbabdc9
Create Date: 2026-06-12 09:39:45.201107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c24aa8d548ba'
down_revision: Union[str, Sequence[str], None] = '14fdecbabdc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_activity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_activity_task_id'), 'task_activity', ['task_id'], unique=False)
    op.add_column('projects', sa.Column('key', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('seq', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Backfill: derive a key prefix from each project name (first 3 letters,
    # uppercased) and number existing tasks per project by creation order.
    op.execute("""
        UPDATE projects
        SET key = UPPER(SUBSTRING(REGEXP_REPLACE(name, '[^a-zA-Z]', '', 'g') FROM 1 FOR 3))
        WHERE key IS NULL
    """)
    op.execute("""
        UPDATE tasks t SET seq = s.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY project_id ORDER BY created_at, id) AS rn
            FROM tasks
        ) s
        WHERE t.id = s.id AND t.seq IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'seq')
    op.drop_column('projects', 'key')
    op.drop_index(op.f('ix_task_activity_task_id'), table_name='task_activity')
    op.drop_table('task_activity')
    # ### end Alembic commands ###
